# This is a basic workflow to help you get started with Actions

name: BE-Main-Service

# Controls when the action will run. 
on:
  push:
    branches: [master]

  pull_request:
      branches:
        - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  be_main_service_java__11_x64:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch from Github 
        uses: actions/checkout@v2
        
      - name: Setup JDK 11.0.10
        uses: actions/setup-java@v1
        with:
         java-version: '11.0.10'
         architecture: x64
         
      - name: Build with maven
        run: mvn dependency:tree clean install
      - name: Deploy artifacts
        run: mvn -batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build spring docker image with maven
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=notabarista/be-main-service
     
      - name: Docker pushing the latest image
        run: docker image push notabarista/be-main-service:latest
